-- All 46 hiragana + 46 katakana (gojuon order) with a short shape mnemonic each.
-- Mastery is tracked separately in user_kana_progress — no level_id, these aren't
-- level-tagged content and aren't part of the long-term SRS deck.

insert into kana_characters (script, character, romaji, mnemonic, sort_order) values
  ('hiragana', 'あ', 'a', 'An antenna on top of a house', 1),
  ('hiragana', 'い', 'i', 'Two strands of hair standing up', 2),
  ('hiragana', 'う', 'u', 'A swirl, like a hook', 3),
  ('hiragana', 'え', 'e', 'A jesters head with a wavy neck', 4),
  ('hiragana', 'お', 'o', 'A woman with a bow in her hair', 5),
  ('hiragana', 'か', 'ka', 'A key with a flag sticking out', 6),
  ('hiragana', 'き', 'ki', 'A key with extra teeth', 7),
  ('hiragana', 'く', 'ku', 'A crooked mouth open wide', 8),
  ('hiragana', 'け', 'ke', 'A key with a leg kicking out', 9),
  ('hiragana', 'こ', 'ko', 'Two ridges stacked, like a caterpillar', 10),
  ('hiragana', 'さ', 'sa', 'A saw with a hook on top', 11),
  ('hiragana', 'し', 'shi', 'A fish hook curling up', 12),
  ('hiragana', 'す', 'su', 'A swirling straw', 13),
  ('hiragana', 'せ', 'se', 'A zipper pulled halfway', 14),
  ('hiragana', 'そ', 'so', 'A zigzag thread', 15),
  ('hiragana', 'た', 'ta', 'A cross with a kicking leg', 16),
  ('hiragana', 'ち', 'chi', 'A cheerleader kicking one leg', 17),
  ('hiragana', 'つ', 'tsu', 'A cresting wave', 18),
  ('hiragana', 'て', 'te', 'A hand held out flat', 19),
  ('hiragana', 'と', 'to', 'A toe with a small hook', 20),
  ('hiragana', 'な', 'na', 'A knot tied with a loop', 21),
  ('hiragana', 'に', 'ni', 'A knee bent with two lines', 22),
  ('hiragana', 'ぬ', 'nu', 'Noodles swirled on a fork', 23),
  ('hiragana', 'ね', 'ne', 'A cat with a curled tail', 24),
  ('hiragana', 'の', 'no', 'A single loop, like shaking the head', 25),
  ('hiragana', 'は', 'ha', 'A stick figure laughing', 26),
  ('hiragana', 'ひ', 'hi', 'A smiling face in profile', 27),
  ('hiragana', 'ふ', 'fu', 'Mount Fuji with two peaks', 28),
  ('hiragana', 'へ', 'he', 'A small mountain peak', 29),
  ('hiragana', 'ほ', 'ho', 'A hoe standing upright', 30),
  ('hiragana', 'ま', 'ma', 'A mother with curled hair', 31),
  ('hiragana', 'み', 'mi', 'A ribbon curled at the bottom', 32),
  ('hiragana', 'む', 'mu', 'A cows face with horns', 33),
  ('hiragana', 'め', 'me', 'An eye looking sideways', 34),
  ('hiragana', 'も', 'mo', 'A fishing hook with a barb', 35),
  ('hiragana', 'や', 'ya', 'A yak with a curved horn', 36),
  ('hiragana', 'ゆ', 'yu', 'A U-turn road sign', 37),
  ('hiragana', 'よ', 'yo', 'A yo-yo hanging on a string', 38),
  ('hiragana', 'ら', 'ra', 'A rabbit with one raised ear', 39),
  ('hiragana', 'り', 'ri', 'Two straight riverbanks', 40),
  ('hiragana', 'る', 'ru', 'A loop-de-loop rollercoaster', 41),
  ('hiragana', 'れ', 're', 'A person kneeling down', 42),
  ('hiragana', 'ろ', 'ro', 'A wrestling ring viewed from above', 43),
  ('hiragana', 'わ', 'wa', 'A wasp with a curled stinger', 44),
  ('hiragana', 'を', 'wo', 'A rare hooked shape, used only as a particle', 45),
  ('hiragana', 'ん', 'n', 'A single swoosh, the only n sound', 46),

  ('katakana', 'ア', 'a', 'An angular open box', 1),
  ('katakana', 'イ', 'i', 'Two legs mid-stride', 2),
  ('katakana', 'ウ', 'u', 'A hood over a hook', 3),
  ('katakana', 'エ', 'e', 'A capital E rotated', 4),
  ('katakana', 'オ', 'o', 'A radio antenna with a crossbar', 5),
  ('katakana', 'カ', 'ka', 'An angular blade', 6),
  ('katakana', 'キ', 'ki', 'A key with straight teeth', 7),
  ('katakana', 'ク', 'ku', 'A boomerang mid-throw', 8),
  ('katakana', 'ケ', 'ke', 'A key with a flag', 9),
  ('katakana', 'コ', 'ko', 'A box missing its right side', 10),
  ('katakana', 'サ', 'sa', 'A folding fan half open', 11),
  ('katakana', 'シ', 'shi', 'Three short dashes, like sushi rolls', 12),
  ('katakana', 'ス', 'su', 'A ski slope with a jump', 13),
  ('katakana', 'セ', 'se', 'A seat with a bent leg', 14),
  ('katakana', 'ソ', 'so', 'A single downward dash', 15),
  ('katakana', 'タ', 'ta', 'A table leg sticking out', 16),
  ('katakana', 'チ', 'chi', 'A chair viewed from the side', 17),
  ('katakana', 'ツ', 'tsu', 'Three claw marks', 18),
  ('katakana', 'テ', 'te', 'A television antenna', 19),
  ('katakana', 'ト', 'to', 'A toe kicking forward', 20),
  ('katakana', 'ナ', 'na', 'A cross with a slash', 21),
  ('katakana', 'ニ', 'ni', 'Two flat, level lines', 22),
  ('katakana', 'ヌ', 'nu', 'A noodle with a swirl at the end', 23),
  ('katakana', 'ネ', 'ne', 'A knot with a small flag', 24),
  ('katakana', 'ノ', 'no', 'A single downward slash', 25),
  ('katakana', 'ハ', 'ha', 'Two legs standing apart, laughing', 26),
  ('katakana', 'ヒ', 'hi', 'A hip bone in profile', 27),
  ('katakana', 'フ', 'fu', 'A sail catching the wind', 28),
  ('katakana', 'ヘ', 'he', 'A small arrow pointing up', 29),
  ('katakana', 'ホ', 'ho', 'A pole with flags on both sides', 30),
  ('katakana', 'マ', 'ma', 'A mast with a flag', 31),
  ('katakana', 'ミ', 'mi', 'Three short waves', 32),
  ('katakana', 'ム', 'mu', 'A cows angular face', 33),
  ('katakana', 'メ', 'me', 'An X-shaped eye', 34),
  ('katakana', 'モ', 'mo', 'A pole with two crossbars', 35),
  ('katakana', 'ヤ', 'ya', 'A slingshot shape', 36),
  ('katakana', 'ユ', 'yu', 'A cup viewed from the side', 37),
  ('katakana', 'ヨ', 'yo', 'Three shelves stacked', 38),
  ('katakana', 'ラ', 'ra', 'A hook with a small flag', 39),
  ('katakana', 'リ', 'ri', 'Two short parallel strokes', 40),
  ('katakana', 'ル', 'ru', 'A loop with a trailing tail', 41),
  ('katakana', 'レ', 're', 'A single downward swoop', 42),
  ('katakana', 'ロ', 'ro', 'A perfect square box', 43),
  ('katakana', 'ワ', 'wa', 'A wine glass shape', 44),
  ('katakana', 'ヲ', 'wo', 'A rare hooked shape, used only as a particle', 45),
  ('katakana', 'ン', 'n', 'A single upward flick, the only n sound', 46)
on conflict (script, character) do nothing;
