-- All 46 hiragana + 46 katakana (gojuon order) with a short shape mnemonic each.
-- Mastery is tracked separately in user_kana_progress — no level_id, these aren't
-- level-tagged content and aren't part of the long-term SRS deck.
--
-- Mnemonic quality rule (see migration 0005): letter-embedding where the romaji
-- genuinely hides in the shape (り = r+i), otherwise a story whose key word
-- STARTS with the kana's sound — the sound tie is always spelled out.

insert into kana_characters (script, character, romaji, mnemonic, sort_order) values
  ('hiragana', 'あ', 'a', 'An antenna bolted to the roof — a(ntenna).', 1),
  ('hiragana', 'い', 'i', 'Two little letter ''i''s standing side by side — i.', 2),
  ('hiragana', 'う', 'u', 'A letter ''u'' tipped sideways, hat on top — u.', 3),
  ('hiragana', 'え', 'e', 'An emperor in flowing robes — e(mperor).', 4),
  ('hiragana', 'お', 'o', 'A big ''o'' hiding in the loop, plus an orbiting dot — o.', 5),
  ('hiragana', 'か', 'ka', 'A karate kick frozen mid-air — ka!', 6),
  ('hiragana', 'き', 'ki', 'A key with two teeth — ki (key).', 7),
  ('hiragana', 'く', 'ku', 'A cuckoo''s open beak — ku.', 8),
  ('hiragana', 'け', 'ke', 'A keg with a tap on its side — ke(g).', 9),
  ('hiragana', 'こ', 'ko', 'Two koi fish gliding in parallel — ko(i).', 10),
  ('hiragana', 'さ', 'sa', 'A saw with a bent handle — sa(w).', 11),
  ('hiragana', 'し', 'shi', 'Her long hair, curling at the tip — shi (she).', 12),
  ('hiragana', 'す', 'su', 'Sucking through a swirly straw — su.', 13),
  ('hiragana', 'せ', 'se', 'A low seat with a backrest — se(at).', 14),
  ('hiragana', 'そ', 'so', 'A needle sewing one zigzag stitch — so (sew).', 15),
  ('hiragana', 'た', 'ta', 'A ''t'' and an ''a'' squeezed together — ta, literally.', 16),
  ('hiragana', 'ち', 'chi', 'A cheerleader mid-kick — chi(eer).', 17),
  ('hiragana', 'つ', 'tsu', 'A tsunami wave curling over — tsu.', 18),
  ('hiragana', 'て', 'te', 'An open hand — て (te) is Japanese for hand.', 19),
  ('hiragana', 'と', 'to', 'A toe with a splinter in it — to(e).', 20),
  ('hiragana', 'な', 'na', 'A nail driven through a loop of rope — na(il).', 21),
  ('hiragana', 'に', 'ni', 'Your knee between two shin lines — ni (knee).', 22),
  ('hiragana', 'ぬ', 'nu', 'A noodle looping back onto the fork — nu(dle).', 23),
  ('hiragana', 'ね', 'ne', 'A cat with a curled tail — ne(ko), Japanese for cat.', 24),
  ('hiragana', 'の', 'no', 'A "no entry" sign — one slash through a circle: no.', 25),
  ('hiragana', 'は', 'ha', '"Ha!" — laughing with a hand on the hip.', 26),
  ('hiragana', 'ひ', 'hi', 'A grin seen from the side — hee! (hi).', 27),
  ('hiragana', 'ふ', 'fu', 'Mount Fuji puffing steam — fu(ji).', 28),
  ('hiragana', 'へ', 'he', 'A heap of sand with one steep side — he(ap).', 29),
  ('hiragana', 'ほ', 'ho', 'A garden hoe leaning on a fence — ho(e).', 30),
  ('hiragana', 'ま', 'ma', 'Mama with her hair in a bun — ma(ma).', 31),
  ('hiragana', 'み', 'mi', 'A music note with a looping tail — mi, as in do-re-mi.', 32),
  ('hiragana', 'む', 'mu', 'A cow''s face mid-moo — mu.', 33),
  ('hiragana', 'め', 'me', 'An eye — め (me) is Japanese for eye.', 34),
  ('hiragana', 'も', 'mo', 'A hook reeling in one more fish — mo(re).', 35),
  ('hiragana', 'や', 'ya', 'A yak''s head with one curved horn — ya(k).', 36),
  ('hiragana', 'ゆ', 'yu', 'A letter ''U'' skewered on a pole — yu.', 37),
  ('hiragana', 'よ', 'yo', 'A yo-yo hanging off a finger — yo.', 38),
  ('hiragana', 'ら', 'ra', 'A rabbit''s ear flopping forward — ra(bbit).', 39),
  ('hiragana', 'り', 'ri', 'The letters ''r'' and ''i'' side by side — り is just ri.', 40),
  ('hiragana', 'る', 'ru', 'A winding route ending in a loop — ru(te).', 41),
  ('hiragana', 'れ', 're', 'A sprinter coiled at the starting line — re(ady)!', 42),
  ('hiragana', 'ろ', 'ro', 'る without its loop — same road (ro), lost the loop (ru).', 43),
  ('hiragana', 'わ', 'wa', 'A wasp with a curled body — wa(sp).', 44),
  ('hiragana', 'を', 'wo', 'Sounds like ''o'' — only ever the object particle; spot it and move on.', 45),
  ('hiragana', 'ん', 'n', 'A cursive lowercase ''n'' — ん literally is n.', 46),

  ('katakana', 'ア', 'a', 'An ''A'' missing its crossbar, swung like an axe — a(xe).', 1),
  ('katakana', 'イ', 'i', 'A capital ''I'' leaning into the wind — i.', 2),
  ('katakana', 'ウ', 'u', 'う''s angular twin: a ''u'' under a pointed roof — u.', 3),
  ('katakana', 'エ', 'e', 'A capital ''E'' rotated to lie flat — e, literally.', 4),
  ('katakana', 'オ', 'o', 'A pole with its flag torn off — o(ff).', 5),
  ('katakana', 'カ', 'ka', 'か minus its flag stroke — the same karate kick: ka.', 6),
  ('katakana', 'キ', 'ki', 'き without the curl — still the key: ki.', 7),
  ('katakana', 'ク', 'ku', 'A cook''s paper hat — ku(k).', 8),
  ('katakana', 'ケ', 'ke', 'A tilted capital ''K'' — ke.', 9),
  ('katakana', 'コ', 'ko', 'A corner bracket — ko(rner).', 10),
  ('katakana', 'サ', 'sa', 'Sardines laid on a grill rack — sa(rdine).', 11),
  ('katakana', 'シ', 'shi', 'し tipped onto its back, plus two drops — shi. Flat strokes = shi.', 12),
  ('katakana', 'ス', 'su', 'A suit jacket tossed over a chair — su(it).', 13),
  ('katakana', 'セ', 'se', 'A crooked number seven — se(ven).', 14),
  ('katakana', 'ソ', 'so', 'One stitch sewn straight down — so (sew). Upright stroke = so.', 15),
  ('katakana', 'タ', 'ta', 'A tadpole darting downward — ta(dpole).', 16),
  ('katakana', 'チ', 'chi', 'The cheerleader again, gone angular — chi(eer).', 17),
  ('katakana', 'ツ', 'tsu', 'つ tipped upright, plus two drops — tsu. Upright strokes = tsu.', 18),
  ('katakana', 'テ', 'te', 'A one-legged table — te, as in テーブル (teeburu).', 19),
  ('katakana', 'ト', 'to', 'A totem pole with one branch — to(tem).', 20),
  ('katakana', 'ナ', 'na', 'A knife mid-slice — ナイフ (naifu) starts with it.', 21),
  ('katakana', 'ニ', 'ni', 'The kanji 二 (two) — ni is literally "two" in Japanese.', 22),
  ('katakana', 'ヌ', 'nu', 'Chopsticks crossing a noodle — nu(dle).', 23),
  ('katakana', 'ネ', 'ne', 'A necktie knotted at the collar — ne(cktie).', 24),
  ('katakana', 'ノ', 'no', 'A single "no!" slash — no.', 25),
  ('katakana', 'ハ', 'ha', 'The kanji 八 (hachi, eight) — same shape, free anchor.', 26),
  ('katakana', 'ヒ', 'hi', 'A heel seen from the side — hi (heel).', 27),
  ('katakana', 'フ', 'fu', 'Just Fuji''s summit ridge, nothing else — fu.', 28),
  ('katakana', 'ヘ', 'he', 'Identical to hiragana へ — one hill, two scripts, free he.', 29),
  ('katakana', 'ホ', 'ho', 'A tree hung with ornaments — ho, ho, ho.', 30),
  ('katakana', 'マ', 'ma', 'A map pin leaning sideways — ma(p).', 31),
  ('katakana', 'ミ', 'mi', 'Kanji 三 (three) slanted — mi, as in mittsu.', 32),
  ('katakana', 'ム', 'mu', 'A cow''s angular muzzle — mu (moo).', 33),
  ('katakana', 'メ', 'me', 'め''s eye gone angular, winking shut — me.', 34),
  ('katakana', 'モ', 'mo', 'も gone angular — same mo, no hook.', 35),
  ('katakana', 'ヤ', 'ya', 'や''s angular twin — same ya.', 36),
  ('katakana', 'ユ', 'yu', 'A ''U'' standing on a baseline — yu.', 37),
  ('katakana', 'ヨ', 'yo', 'A yoke rack seen from the side — yo(ke).', 38),
  ('katakana', 'ラ', 'ra', 'A ramp under a flat roof — ra(mp).', 39),
  ('katakana', 'リ', 'ri', 'り straightened out — still just r + i: ri.', 40),
  ('katakana', 'ル', 'ru', 'Forked roots, one tip curling up — ru (root).', 41),
  ('katakana', 'レ', 're', 'A razor blade seen edge-on — re(zor).', 42),
  ('katakana', 'ロ', 'ro', 'A robot''s square mouth — ro(bot).', 43),
  ('katakana', 'ワ', 'wa', 'An upside-down wine glass — wa(ine).', 44),
  ('katakana', 'ヲ', 'wo', 'Sounds like ''o'' — vanishingly rare; recognize it and move on.', 45),
  ('katakana', 'ン', 'n', 'One flat flick — n. Flat = ン (n); upright = ソ (so).', 46)
on conflict (script, character) do nothing;

-- Dakuten/handakuten, yōon, sokuon, and chōon: these are systematic modifications
-- of characters already learned above, not new shapes — mnemonics teach the rule
-- (voicing, gliding, doubling, lengthening) rather than inventing a fresh story
-- for each of the 119 rows, which is also how these are actually learned.

insert into kana_characters (script, character, romaji, mnemonic, sort_order) values
  ('hiragana', 'が', 'ga', 'か plus dakuten (two small strokes) voices k into g', 47),
  ('hiragana', 'ぎ', 'gi', 'き plus dakuten voices k into g', 48),
  ('hiragana', 'ぐ', 'gu', 'く plus dakuten voices k into g', 49),
  ('hiragana', 'げ', 'ge', 'け plus dakuten voices k into g', 50),
  ('hiragana', 'ご', 'go', 'こ plus dakuten voices k into g', 51),
  ('hiragana', 'ざ', 'za', 'さ plus dakuten voices s into z', 52),
  ('hiragana', 'じ', 'ji', 'し plus dakuten voices s into a soft j sound', 53),
  ('hiragana', 'ず', 'zu', 'す plus dakuten voices s into z', 54),
  ('hiragana', 'ぜ', 'ze', 'せ plus dakuten voices s into z', 55),
  ('hiragana', 'ぞ', 'zo', 'そ plus dakuten voices s into z', 56),
  ('hiragana', 'だ', 'da', 'た plus dakuten voices t into d', 57),
  ('hiragana', 'ぢ', 'ji', 'ち plus dakuten, pronounced the same as じ', 58),
  ('hiragana', 'づ', 'zu', 'つ plus dakuten, pronounced the same as ず', 59),
  ('hiragana', 'で', 'de', 'て plus dakuten voices t into d', 60),
  ('hiragana', 'ど', 'do', 'と plus dakuten voices t into d', 61),
  ('hiragana', 'ば', 'ba', 'は plus dakuten voices h into b', 62),
  ('hiragana', 'び', 'bi', 'ひ plus dakuten voices h into b', 63),
  ('hiragana', 'ぶ', 'bu', 'ふ plus dakuten voices h into b', 64),
  ('hiragana', 'べ', 'be', 'へ plus dakuten voices h into b', 65),
  ('hiragana', 'ぼ', 'bo', 'ほ plus dakuten voices h into b', 66),
  ('hiragana', 'ぱ', 'pa', 'は plus handakuten (small circle) makes a crisp p sound', 67),
  ('hiragana', 'ぴ', 'pi', 'ひ plus handakuten makes a crisp p sound', 68),
  ('hiragana', 'ぷ', 'pu', 'ふ plus handakuten makes a crisp p sound', 69),
  ('hiragana', 'ぺ', 'pe', 'へ plus handakuten makes a crisp p sound', 70),
  ('hiragana', 'ぽ', 'po', 'ほ plus handakuten makes a crisp p sound', 71),
  ('hiragana', 'きゃ', 'kya', 'き plus a small や glides into a kya sound', 72),
  ('hiragana', 'きゅ', 'kyu', 'き plus a small ゆ glides into a kyu sound', 73),
  ('hiragana', 'きょ', 'kyo', 'き plus a small よ glides into a kyo sound', 74),
  ('hiragana', 'しゃ', 'sha', 'し plus a small や glides into a sha sound', 75),
  ('hiragana', 'しゅ', 'shu', 'し plus a small ゆ glides into a shu sound', 76),
  ('hiragana', 'しょ', 'sho', 'し plus a small よ glides into a sho sound', 77),
  ('hiragana', 'ちゃ', 'cha', 'ち plus a small や glides into a cha sound', 78),
  ('hiragana', 'ちゅ', 'chu', 'ち plus a small ゆ glides into a chu sound', 79),
  ('hiragana', 'ちょ', 'cho', 'ち plus a small よ glides into a cho sound', 80),
  ('hiragana', 'にゃ', 'nya', 'に plus a small や glides into a nya sound', 81),
  ('hiragana', 'にゅ', 'nyu', 'に plus a small ゆ glides into a nyu sound', 82),
  ('hiragana', 'にょ', 'nyo', 'に plus a small よ glides into a nyo sound', 83),
  ('hiragana', 'ひゃ', 'hya', 'ひ plus a small や glides into a hya sound', 84),
  ('hiragana', 'ひゅ', 'hyu', 'ひ plus a small ゆ glides into a hyu sound', 85),
  ('hiragana', 'ひょ', 'hyo', 'ひ plus a small よ glides into a hyo sound', 86),
  ('hiragana', 'みゃ', 'mya', 'み plus a small や glides into a mya sound', 87),
  ('hiragana', 'みゅ', 'myu', 'み plus a small ゆ glides into a myu sound', 88),
  ('hiragana', 'みょ', 'myo', 'み plus a small よ glides into a myo sound', 89),
  ('hiragana', 'りゃ', 'rya', 'り plus a small や glides into a rya sound', 90),
  ('hiragana', 'りゅ', 'ryu', 'り plus a small ゆ glides into a ryu sound', 91),
  ('hiragana', 'りょ', 'ryo', 'り plus a small よ glides into a ryo sound', 92),
  ('hiragana', 'ぎゃ', 'gya', 'ぎ plus a small や glides into a gya sound', 93),
  ('hiragana', 'ぎゅ', 'gyu', 'ぎ plus a small ゆ glides into a gyu sound', 94),
  ('hiragana', 'ぎょ', 'gyo', 'ぎ plus a small よ glides into a gyo sound', 95),
  ('hiragana', 'じゃ', 'ja', 'じ plus a small や glides into a ja sound', 96),
  ('hiragana', 'じゅ', 'ju', 'じ plus a small ゆ glides into a ju sound', 97),
  ('hiragana', 'じょ', 'jo', 'じ plus a small よ glides into a jo sound', 98),
  ('hiragana', 'びゃ', 'bya', 'び plus a small や glides into a bya sound', 99),
  ('hiragana', 'びゅ', 'byu', 'び plus a small ゆ glides into a byu sound', 100),
  ('hiragana', 'びょ', 'byo', 'び plus a small よ glides into a byo sound', 101),
  ('hiragana', 'ぴゃ', 'pya', 'ぴ plus a small や glides into a pya sound', 102),
  ('hiragana', 'ぴゅ', 'pyu', 'ぴ plus a small ゆ glides into a pyu sound', 103),
  ('hiragana', 'ぴょ', 'pyo', 'ぴ plus a small よ glides into a pyo sound', 104),
  ('hiragana', 'っ', '(sokuon)', 'A small っ — silent on its own, but doubles the consonant that follows, like in がっこう', 105),

  ('katakana', 'ガ', 'ga', 'カ plus dakuten voices k into g', 47),
  ('katakana', 'ギ', 'gi', 'キ plus dakuten voices k into g', 48),
  ('katakana', 'グ', 'gu', 'ク plus dakuten voices k into g', 49),
  ('katakana', 'ゲ', 'ge', 'ケ plus dakuten voices k into g', 50),
  ('katakana', 'ゴ', 'go', 'コ plus dakuten voices k into g', 51),
  ('katakana', 'ザ', 'za', 'サ plus dakuten voices s into z', 52),
  ('katakana', 'ジ', 'ji', 'シ plus dakuten voices s into a soft j sound', 53),
  ('katakana', 'ズ', 'zu', 'ス plus dakuten voices s into z', 54),
  ('katakana', 'ゼ', 'ze', 'セ plus dakuten voices s into z', 55),
  ('katakana', 'ゾ', 'zo', 'ソ plus dakuten voices s into z', 56),
  ('katakana', 'ダ', 'da', 'タ plus dakuten voices t into d', 57),
  ('katakana', 'ヂ', 'ji', 'チ plus dakuten, pronounced the same as ジ', 58),
  ('katakana', 'ヅ', 'zu', 'ツ plus dakuten, pronounced the same as ズ', 59),
  ('katakana', 'デ', 'de', 'テ plus dakuten voices t into d', 60),
  ('katakana', 'ド', 'do', 'ト plus dakuten voices t into d', 61),
  ('katakana', 'バ', 'ba', 'ハ plus dakuten voices h into b', 62),
  ('katakana', 'ビ', 'bi', 'ヒ plus dakuten voices h into b', 63),
  ('katakana', 'ブ', 'bu', 'フ plus dakuten voices h into b', 64),
  ('katakana', 'ベ', 'be', 'ヘ plus dakuten voices h into b', 65),
  ('katakana', 'ボ', 'bo', 'ホ plus dakuten voices h into b', 66),
  ('katakana', 'パ', 'pa', 'ハ plus handakuten (small circle) makes a crisp p sound', 67),
  ('katakana', 'ピ', 'pi', 'ヒ plus handakuten makes a crisp p sound', 68),
  ('katakana', 'プ', 'pu', 'フ plus handakuten makes a crisp p sound', 69),
  ('katakana', 'ペ', 'pe', 'ヘ plus handakuten makes a crisp p sound', 70),
  ('katakana', 'ポ', 'po', 'ホ plus handakuten makes a crisp p sound', 71),
  ('katakana', 'キャ', 'kya', 'キ plus a small ヤ glides into a kya sound', 72),
  ('katakana', 'キュ', 'kyu', 'キ plus a small ユ glides into a kyu sound', 73),
  ('katakana', 'キョ', 'kyo', 'キ plus a small ヨ glides into a kyo sound', 74),
  ('katakana', 'シャ', 'sha', 'シ plus a small ヤ glides into a sha sound', 75),
  ('katakana', 'シュ', 'shu', 'シ plus a small ユ glides into a shu sound', 76),
  ('katakana', 'ショ', 'sho', 'シ plus a small ヨ glides into a sho sound', 77),
  ('katakana', 'チャ', 'cha', 'チ plus a small ヤ glides into a cha sound', 78),
  ('katakana', 'チュ', 'chu', 'チ plus a small ユ glides into a chu sound', 79),
  ('katakana', 'チョ', 'cho', 'チ plus a small ヨ glides into a cho sound', 80),
  ('katakana', 'ニャ', 'nya', 'ニ plus a small ヤ glides into a nya sound', 81),
  ('katakana', 'ニュ', 'nyu', 'ニ plus a small ユ glides into a nyu sound', 82),
  ('katakana', 'ニョ', 'nyo', 'ニ plus a small ヨ glides into a nyo sound', 83),
  ('katakana', 'ヒャ', 'hya', 'ヒ plus a small ヤ glides into a hya sound', 84),
  ('katakana', 'ヒュ', 'hyu', 'ヒ plus a small ユ glides into a hyu sound', 85),
  ('katakana', 'ヒョ', 'hyo', 'ヒ plus a small ヨ glides into a hyo sound', 86),
  ('katakana', 'ミャ', 'mya', 'ミ plus a small ヤ glides into a mya sound', 87),
  ('katakana', 'ミュ', 'myu', 'ミ plus a small ユ glides into a myu sound', 88),
  ('katakana', 'ミョ', 'myo', 'ミ plus a small ヨ glides into a myo sound', 89),
  ('katakana', 'リャ', 'rya', 'リ plus a small ヤ glides into a rya sound', 90),
  ('katakana', 'リュ', 'ryu', 'リ plus a small ユ glides into a ryu sound', 91),
  ('katakana', 'リョ', 'ryo', 'リ plus a small ヨ glides into a ryo sound', 92),
  ('katakana', 'ギャ', 'gya', 'ギ plus a small ヤ glides into a gya sound', 93),
  ('katakana', 'ギュ', 'gyu', 'ギ plus a small ユ glides into a gyu sound', 94),
  ('katakana', 'ギョ', 'gyo', 'ギ plus a small ヨ glides into a gyo sound', 95),
  ('katakana', 'ジャ', 'ja', 'ジ plus a small ヤ glides into a ja sound', 96),
  ('katakana', 'ジュ', 'ju', 'ジ plus a small ユ glides into a ju sound', 97),
  ('katakana', 'ジョ', 'jo', 'ジ plus a small ヨ glides into a jo sound', 98),
  ('katakana', 'ビャ', 'bya', 'ビ plus a small ヤ glides into a bya sound', 99),
  ('katakana', 'ビュ', 'byu', 'ビ plus a small ユ glides into a byu sound', 100),
  ('katakana', 'ビョ', 'byo', 'ビ plus a small ヨ glides into a byo sound', 101),
  ('katakana', 'ピャ', 'pya', 'ピ plus a small ヤ glides into a pya sound', 102),
  ('katakana', 'ピュ', 'pyu', 'ピ plus a small ユ glides into a pyu sound', 103),
  ('katakana', 'ピョ', 'pyo', 'ピ plus a small ヨ glides into a pyo sound', 104),
  ('katakana', 'ッ', '(sokuon)', 'A small ッ — silent on its own, but doubles the consonant that follows, like in ロケット', 105),
  ('katakana', 'ー', '(chōon)', 'A dash — stretches the previous vowel sound longer, like in コーヒー', 106)
on conflict (script, character) do nothing;
