-- All 46 hiragana + 46 katakana (gojuon order) with a short shape mnemonic each.
-- Mastery is tracked separately in user_kana_progress — no level_id, these aren't
-- level-tagged content and aren't part of the long-term SRS deck.

insert into kana_characters (script, character, romaji, mnemonic, sort_order) values
  ('hiragana', 'あ', 'a', 'An antenna on top of a house', 1),
  ('hiragana', 'い', 'i', 'Two strands of hair standing up', 2),
  ('hiragana', 'う', 'u', 'A swirl, like a hook', 3),
  ('hiragana', 'え', 'e', 'A jesters head with a wavy neck', 4),
  ('hiragana', 'お', 'o', 'A woman with a bow in her hair', 5),
  ('hiragana', 'か', 'ka', 'A key with a flag sticking out', 6),
  ('hiragana', 'き', 'ki', 'A key with extra teeth', 7),
  ('hiragana', 'く', 'ku', 'A crooked mouth open wide', 8),
  ('hiragana', 'け', 'ke', 'A key with a leg kicking out', 9),
  ('hiragana', 'こ', 'ko', 'Two ridges stacked, like a caterpillar', 10),
  ('hiragana', 'さ', 'sa', 'A saw with a hook on top', 11),
  ('hiragana', 'し', 'shi', 'A fish hook curling up', 12),
  ('hiragana', 'す', 'su', 'A swirling straw', 13),
  ('hiragana', 'せ', 'se', 'A zipper pulled halfway', 14),
  ('hiragana', 'そ', 'so', 'A zigzag thread', 15),
  ('hiragana', 'た', 'ta', 'A cross with a kicking leg', 16),
  ('hiragana', 'ち', 'chi', 'A cheerleader kicking one leg', 17),
  ('hiragana', 'つ', 'tsu', 'A cresting wave', 18),
  ('hiragana', 'て', 'te', 'A hand held out flat', 19),
  ('hiragana', 'と', 'to', 'A toe with a small hook', 20),
  ('hiragana', 'な', 'na', 'A knot tied with a loop', 21),
  ('hiragana', 'に', 'ni', 'A knee bent with two lines', 22),
  ('hiragana', 'ぬ', 'nu', 'Noodles swirled on a fork', 23),
  ('hiragana', 'ね', 'ne', 'A cat with a curled tail', 24),
  ('hiragana', 'の', 'no', 'A single loop, like shaking the head', 25),
  ('hiragana', 'は', 'ha', 'A stick figure laughing', 26),
  ('hiragana', 'ひ', 'hi', 'A smiling face in profile', 27),
  ('hiragana', 'ふ', 'fu', 'Mount Fuji with two peaks', 28),
  ('hiragana', 'へ', 'he', 'A small mountain peak', 29),
  ('hiragana', 'ほ', 'ho', 'A hoe standing upright', 30),
  ('hiragana', 'ま', 'ma', 'A mother with curled hair', 31),
  ('hiragana', 'み', 'mi', 'A ribbon curled at the bottom', 32),
  ('hiragana', 'む', 'mu', 'A cows face with horns', 33),
  ('hiragana', 'め', 'me', 'An eye looking sideways', 34),
  ('hiragana', 'も', 'mo', 'A fishing hook with a barb', 35),
  ('hiragana', 'や', 'ya', 'A yak with a curved horn', 36),
  ('hiragana', 'ゆ', 'yu', 'A U-turn road sign', 37),
  ('hiragana', 'よ', 'yo', 'A yo-yo hanging on a string', 38),
  ('hiragana', 'ら', 'ra', 'A rabbit with one raised ear', 39),
  ('hiragana', 'り', 'ri', 'Two straight riverbanks', 40),
  ('hiragana', 'る', 'ru', 'A loop-de-loop rollercoaster', 41),
  ('hiragana', 'れ', 're', 'A person kneeling down', 42),
  ('hiragana', 'ろ', 'ro', 'A wrestling ring viewed from above', 43),
  ('hiragana', 'わ', 'wa', 'A wasp with a curled stinger', 44),
  ('hiragana', 'を', 'wo', 'A rare hooked shape, used only as a particle', 45),
  ('hiragana', 'ん', 'n', 'A single swoosh, the only n sound', 46),

  ('katakana', 'ア', 'a', 'An angular open box', 1),
  ('katakana', 'イ', 'i', 'Two legs mid-stride', 2),
  ('katakana', 'ウ', 'u', 'A hood over a hook', 3),
  ('katakana', 'エ', 'e', 'A capital E rotated', 4),
  ('katakana', 'オ', 'o', 'A radio antenna with a crossbar', 5),
  ('katakana', 'カ', 'ka', 'An angular blade', 6),
  ('katakana', 'キ', 'ki', 'A key with straight teeth', 7),
  ('katakana', 'ク', 'ku', 'A boomerang mid-throw', 8),
  ('katakana', 'ケ', 'ke', 'A key with a flag', 9),
  ('katakana', 'コ', 'ko', 'A box missing its right side', 10),
  ('katakana', 'サ', 'sa', 'A folding fan half open', 11),
  ('katakana', 'シ', 'shi', 'Three short dashes, like sushi rolls', 12),
  ('katakana', 'ス', 'su', 'A ski slope with a jump', 13),
  ('katakana', 'セ', 'se', 'A seat with a bent leg', 14),
  ('katakana', 'ソ', 'so', 'A single downward dash', 15),
  ('katakana', 'タ', 'ta', 'A table leg sticking out', 16),
  ('katakana', 'チ', 'chi', 'A chair viewed from the side', 17),
  ('katakana', 'ツ', 'tsu', 'Three claw marks', 18),
  ('katakana', 'テ', 'te', 'A television antenna', 19),
  ('katakana', 'ト', 'to', 'A toe kicking forward', 20),
  ('katakana', 'ナ', 'na', 'A cross with a slash', 21),
  ('katakana', 'ニ', 'ni', 'Two flat, level lines', 22),
  ('katakana', 'ヌ', 'nu', 'A noodle with a swirl at the end', 23),
  ('katakana', 'ネ', 'ne', 'A knot with a small flag', 24),
  ('katakana', 'ノ', 'no', 'A single downward slash', 25),
  ('katakana', 'ハ', 'ha', 'Two legs standing apart, laughing', 26),
  ('katakana', 'ヒ', 'hi', 'A hip bone in profile', 27),
  ('katakana', 'フ', 'fu', 'A sail catching the wind', 28),
  ('katakana', 'ヘ', 'he', 'A small arrow pointing up', 29),
  ('katakana', 'ホ', 'ho', 'A pole with flags on both sides', 30),
  ('katakana', 'マ', 'ma', 'A mast with a flag', 31),
  ('katakana', 'ミ', 'mi', 'Three short waves', 32),
  ('katakana', 'ム', 'mu', 'A cows angular face', 33),
  ('katakana', 'メ', 'me', 'An X-shaped eye', 34),
  ('katakana', 'モ', 'mo', 'A pole with two crossbars', 35),
  ('katakana', 'ヤ', 'ya', 'A slingshot shape', 36),
  ('katakana', 'ユ', 'yu', 'A cup viewed from the side', 37),
  ('katakana', 'ヨ', 'yo', 'Three shelves stacked', 38),
  ('katakana', 'ラ', 'ra', 'A hook with a small flag', 39),
  ('katakana', 'リ', 'ri', 'Two short parallel strokes', 40),
  ('katakana', 'ル', 'ru', 'A loop with a trailing tail', 41),
  ('katakana', 'レ', 're', 'A single downward swoop', 42),
  ('katakana', 'ロ', 'ro', 'A perfect square box', 43),
  ('katakana', 'ワ', 'wa', 'A wine glass shape', 44),
  ('katakana', 'ヲ', 'wo', 'A rare hooked shape, used only as a particle', 45),
  ('katakana', 'ン', 'n', 'A single upward flick, the only n sound', 46)
on conflict (script, character) do nothing;

-- Dakuten/handakuten, yōon, sokuon, and chōon: these are systematic modifications
-- of characters already learned above, not new shapes — mnemonics teach the rule
-- (voicing, gliding, doubling, lengthening) rather than inventing a fresh story
-- for each of the 119 rows, which is also how these are actually learned.

insert into kana_characters (script, character, romaji, mnemonic, sort_order) values
  ('hiragana', 'が', 'ga', 'か plus dakuten (two small strokes) voices k into g', 47),
  ('hiragana', 'ぎ', 'gi', 'き plus dakuten voices k into g', 48),
  ('hiragana', 'ぐ', 'gu', 'く plus dakuten voices k into g', 49),
  ('hiragana', 'げ', 'ge', 'け plus dakuten voices k into g', 50),
  ('hiragana', 'ご', 'go', 'こ plus dakuten voices k into g', 51),
  ('hiragana', 'ざ', 'za', 'さ plus dakuten voices s into z', 52),
  ('hiragana', 'じ', 'ji', 'し plus dakuten voices s into a soft j sound', 53),
  ('hiragana', 'ず', 'zu', 'す plus dakuten voices s into z', 54),
  ('hiragana', 'ぜ', 'ze', 'せ plus dakuten voices s into z', 55),
  ('hiragana', 'ぞ', 'zo', 'そ plus dakuten voices s into z', 56),
  ('hiragana', 'だ', 'da', 'た plus dakuten voices t into d', 57),
  ('hiragana', 'ぢ', 'ji', 'ち plus dakuten, pronounced the same as じ', 58),
  ('hiragana', 'づ', 'zu', 'つ plus dakuten, pronounced the same as ず', 59),
  ('hiragana', 'で', 'de', 'て plus dakuten voices t into d', 60),
  ('hiragana', 'ど', 'do', 'と plus dakuten voices t into d', 61),
  ('hiragana', 'ば', 'ba', 'は plus dakuten voices h into b', 62),
  ('hiragana', 'び', 'bi', 'ひ plus dakuten voices h into b', 63),
  ('hiragana', 'ぶ', 'bu', 'ふ plus dakuten voices h into b', 64),
  ('hiragana', 'べ', 'be', 'へ plus dakuten voices h into b', 65),
  ('hiragana', 'ぼ', 'bo', 'ほ plus dakuten voices h into b', 66),
  ('hiragana', 'ぱ', 'pa', 'は plus handakuten (small circle) makes a crisp p sound', 67),
  ('hiragana', 'ぴ', 'pi', 'ひ plus handakuten makes a crisp p sound', 68),
  ('hiragana', 'ぷ', 'pu', 'ふ plus handakuten makes a crisp p sound', 69),
  ('hiragana', 'ぺ', 'pe', 'へ plus handakuten makes a crisp p sound', 70),
  ('hiragana', 'ぽ', 'po', 'ほ plus handakuten makes a crisp p sound', 71),
  ('hiragana', 'きゃ', 'kya', 'き plus a small や glides into a kya sound', 72),
  ('hiragana', 'きゅ', 'kyu', 'き plus a small ゆ glides into a kyu sound', 73),
  ('hiragana', 'きょ', 'kyo', 'き plus a small よ glides into a kyo sound', 74),
  ('hiragana', 'しゃ', 'sha', 'し plus a small や glides into a sha sound', 75),
  ('hiragana', 'しゅ', 'shu', 'し plus a small ゆ glides into a shu sound', 76),
  ('hiragana', 'しょ', 'sho', 'し plus a small よ glides into a sho sound', 77),
  ('hiragana', 'ちゃ', 'cha', 'ち plus a small や glides into a cha sound', 78),
  ('hiragana', 'ちゅ', 'chu', 'ち plus a small ゆ glides into a chu sound', 79),
  ('hiragana', 'ちょ', 'cho', 'ち plus a small よ glides into a cho sound', 80),
  ('hiragana', 'にゃ', 'nya', 'に plus a small や glides into a nya sound', 81),
  ('hiragana', 'にゅ', 'nyu', 'に plus a small ゆ glides into a nyu sound', 82),
  ('hiragana', 'にょ', 'nyo', 'に plus a small よ glides into a nyo sound', 83),
  ('hiragana', 'ひゃ', 'hya', 'ひ plus a small や glides into a hya sound', 84),
  ('hiragana', 'ひゅ', 'hyu', 'ひ plus a small ゆ glides into a hyu sound', 85),
  ('hiragana', 'ひょ', 'hyo', 'ひ plus a small よ glides into a hyo sound', 86),
  ('hiragana', 'みゃ', 'mya', 'み plus a small や glides into a mya sound', 87),
  ('hiragana', 'みゅ', 'myu', 'み plus a small ゆ glides into a myu sound', 88),
  ('hiragana', 'みょ', 'myo', 'み plus a small よ glides into a myo sound', 89),
  ('hiragana', 'りゃ', 'rya', 'り plus a small や glides into a rya sound', 90),
  ('hiragana', 'りゅ', 'ryu', 'り plus a small ゆ glides into a ryu sound', 91),
  ('hiragana', 'りょ', 'ryo', 'り plus a small よ glides into a ryo sound', 92),
  ('hiragana', 'ぎゃ', 'gya', 'ぎ plus a small や glides into a gya sound', 93),
  ('hiragana', 'ぎゅ', 'gyu', 'ぎ plus a small ゆ glides into a gyu sound', 94),
  ('hiragana', 'ぎょ', 'gyo', 'ぎ plus a small よ glides into a gyo sound', 95),
  ('hiragana', 'じゃ', 'ja', 'じ plus a small や glides into a ja sound', 96),
  ('hiragana', 'じゅ', 'ju', 'じ plus a small ゆ glides into a ju sound', 97),
  ('hiragana', 'じょ', 'jo', 'じ plus a small よ glides into a jo sound', 98),
  ('hiragana', 'びゃ', 'bya', 'び plus a small や glides into a bya sound', 99),
  ('hiragana', 'びゅ', 'byu', 'び plus a small ゆ glides into a byu sound', 100),
  ('hiragana', 'びょ', 'byo', 'び plus a small よ glides into a byo sound', 101),
  ('hiragana', 'ぴゃ', 'pya', 'ぴ plus a small や glides into a pya sound', 102),
  ('hiragana', 'ぴゅ', 'pyu', 'ぴ plus a small ゆ glides into a pyu sound', 103),
  ('hiragana', 'ぴょ', 'pyo', 'ぴ plus a small よ glides into a pyo sound', 104),
  ('hiragana', 'っ', '(sokuon)', 'A small っ — silent on its own, but doubles the consonant that follows, like in がっこう', 105),

  ('katakana', 'ガ', 'ga', 'カ plus dakuten voices k into g', 47),
  ('katakana', 'ギ', 'gi', 'キ plus dakuten voices k into g', 48),
  ('katakana', 'グ', 'gu', 'ク plus dakuten voices k into g', 49),
  ('katakana', 'ゲ', 'ge', 'ケ plus dakuten voices k into g', 50),
  ('katakana', 'ゴ', 'go', 'コ plus dakuten voices k into g', 51),
  ('katakana', 'ザ', 'za', 'サ plus dakuten voices s into z', 52),
  ('katakana', 'ジ', 'ji', 'シ plus dakuten voices s into a soft j sound', 53),
  ('katakana', 'ズ', 'zu', 'ス plus dakuten voices s into z', 54),
  ('katakana', 'ゼ', 'ze', 'セ plus dakuten voices s into z', 55),
  ('katakana', 'ゾ', 'zo', 'ソ plus dakuten voices s into z', 56),
  ('katakana', 'ダ', 'da', 'タ plus dakuten voices t into d', 57),
  ('katakana', 'ヂ', 'ji', 'チ plus dakuten, pronounced the same as ジ', 58),
  ('katakana', 'ヅ', 'zu', 'ツ plus dakuten, pronounced the same as ズ', 59),
  ('katakana', 'デ', 'de', 'テ plus dakuten voices t into d', 60),
  ('katakana', 'ド', 'do', 'ト plus dakuten voices t into d', 61),
  ('katakana', 'バ', 'ba', 'ハ plus dakuten voices h into b', 62),
  ('katakana', 'ビ', 'bi', 'ヒ plus dakuten voices h into b', 63),
  ('katakana', 'ブ', 'bu', 'フ plus dakuten voices h into b', 64),
  ('katakana', 'ベ', 'be', 'ヘ plus dakuten voices h into b', 65),
  ('katakana', 'ボ', 'bo', 'ホ plus dakuten voices h into b', 66),
  ('katakana', 'パ', 'pa', 'ハ plus handakuten (small circle) makes a crisp p sound', 67),
  ('katakana', 'ピ', 'pi', 'ヒ plus handakuten makes a crisp p sound', 68),
  ('katakana', 'プ', 'pu', 'フ plus handakuten makes a crisp p sound', 69),
  ('katakana', 'ペ', 'pe', 'ヘ plus handakuten makes a crisp p sound', 70),
  ('katakana', 'ポ', 'po', 'ホ plus handakuten makes a crisp p sound', 71),
  ('katakana', 'キャ', 'kya', 'キ plus a small ヤ glides into a kya sound', 72),
  ('katakana', 'キュ', 'kyu', 'キ plus a small ユ glides into a kyu sound', 73),
  ('katakana', 'キョ', 'kyo', 'キ plus a small ヨ glides into a kyo sound', 74),
  ('katakana', 'シャ', 'sha', 'シ plus a small ヤ glides into a sha sound', 75),
  ('katakana', 'シュ', 'shu', 'シ plus a small ユ glides into a shu sound', 76),
  ('katakana', 'ショ', 'sho', 'シ plus a small ヨ glides into a sho sound', 77),
  ('katakana', 'チャ', 'cha', 'チ plus a small ヤ glides into a cha sound', 78),
  ('katakana', 'チュ', 'chu', 'チ plus a small ユ glides into a chu sound', 79),
  ('katakana', 'チョ', 'cho', 'チ plus a small ヨ glides into a cho sound', 80),
  ('katakana', 'ニャ', 'nya', 'ニ plus a small ヤ glides into a nya sound', 81),
  ('katakana', 'ニュ', 'nyu', 'ニ plus a small ユ glides into a nyu sound', 82),
  ('katakana', 'ニョ', 'nyo', 'ニ plus a small ヨ glides into a nyo sound', 83),
  ('katakana', 'ヒャ', 'hya', 'ヒ plus a small ヤ glides into a hya sound', 84),
  ('katakana', 'ヒュ', 'hyu', 'ヒ plus a small ユ glides into a hyu sound', 85),
  ('katakana', 'ヒョ', 'hyo', 'ヒ plus a small ヨ glides into a hyo sound', 86),
  ('katakana', 'ミャ', 'mya', 'ミ plus a small ヤ glides into a mya sound', 87),
  ('katakana', 'ミュ', 'myu', 'ミ plus a small ユ glides into a myu sound', 88),
  ('katakana', 'ミョ', 'myo', 'ミ plus a small ヨ glides into a myo sound', 89),
  ('katakana', 'リャ', 'rya', 'リ plus a small ヤ glides into a rya sound', 90),
  ('katakana', 'リュ', 'ryu', 'リ plus a small ユ glides into a ryu sound', 91),
  ('katakana', 'リョ', 'ryo', 'リ plus a small ヨ glides into a ryo sound', 92),
  ('katakana', 'ギャ', 'gya', 'ギ plus a small ヤ glides into a gya sound', 93),
  ('katakana', 'ギュ', 'gyu', 'ギ plus a small ユ glides into a gyu sound', 94),
  ('katakana', 'ギョ', 'gyo', 'ギ plus a small ヨ glides into a gyo sound', 95),
  ('katakana', 'ジャ', 'ja', 'ジ plus a small ヤ glides into a ja sound', 96),
  ('katakana', 'ジュ', 'ju', 'ジ plus a small ユ glides into a ju sound', 97),
  ('katakana', 'ジョ', 'jo', 'ジ plus a small ヨ glides into a jo sound', 98),
  ('katakana', 'ビャ', 'bya', 'ビ plus a small ヤ glides into a bya sound', 99),
  ('katakana', 'ビュ', 'byu', 'ビ plus a small ユ glides into a byu sound', 100),
  ('katakana', 'ビョ', 'byo', 'ビ plus a small ヨ glides into a byo sound', 101),
  ('katakana', 'ピャ', 'pya', 'ピ plus a small ヤ glides into a pya sound', 102),
  ('katakana', 'ピュ', 'pyu', 'ピ plus a small ユ glides into a pyu sound', 103),
  ('katakana', 'ピョ', 'pyo', 'ピ plus a small ヨ glides into a pyo sound', 104),
  ('katakana', 'ッ', '(sokuon)', 'A small ッ — silent on its own, but doubles the consonant that follows, like in ロケット', 105),
  ('katakana', 'ー', '(chōon)', 'A dash — stretches the previous vowel sound longer, like in コーヒー', 106)
on conflict (script, character) do nothing;
