-- Mnemonic rewrite for the 92 core kana. The old set had shape descriptions with
-- missing or broken sound anchors (せ = "zipper" points at z, not se). New rule:
-- letter-embedding where the romaji genuinely hides in the shape (り = r+i),
-- otherwise a story whose key word STARTS with the kana's sound, always spelled
-- out. Extended rows (dakuten/yōon/sokuon/chōon) keep their rule-teaching lines.

update kana_characters as k
set mnemonic = v.mnemonic
from (values
  ('hiragana', 'あ', 'An antenna bolted to the roof — a(ntenna).'),
  ('hiragana', 'い', 'Two little letter ''i''s standing side by side — i.'),
  ('hiragana', 'う', 'A letter ''u'' tipped sideways, hat on top — u.'),
  ('hiragana', 'え', 'An emperor in flowing robes — e(mperor).'),
  ('hiragana', 'お', 'A big ''o'' hiding in the loop, plus an orbiting dot — o.'),
  ('hiragana', 'か', 'A karate kick frozen mid-air — ka!'),
  ('hiragana', 'き', 'A key with two teeth — ki (key).'),
  ('hiragana', 'く', 'A cuckoo''s open beak — ku.'),
  ('hiragana', 'け', 'A keg with a tap on its side — ke(g).'),
  ('hiragana', 'こ', 'Two koi fish gliding in parallel — ko(i).'),
  ('hiragana', 'さ', 'A saw with a bent handle — sa(w).'),
  ('hiragana', 'し', 'Her long hair, curling at the tip — shi (she).'),
  ('hiragana', 'す', 'Sucking through a swirly straw — su.'),
  ('hiragana', 'せ', 'A low seat with a backrest — se(at).'),
  ('hiragana', 'そ', 'A needle sewing one zigzag stitch — so (sew).'),
  ('hiragana', 'た', 'A ''t'' and an ''a'' squeezed together — ta, literally.'),
  ('hiragana', 'ち', 'A cheerleader mid-kick — chi(eer).'),
  ('hiragana', 'つ', 'A tsunami wave curling over — tsu.'),
  ('hiragana', 'て', 'An open hand — て (te) is Japanese for hand.'),
  ('hiragana', 'と', 'A toe with a splinter in it — to(e).'),
  ('hiragana', 'な', 'A nail driven through a loop of rope — na(il).'),
  ('hiragana', 'に', 'Your knee between two shin lines — ni (knee).'),
  ('hiragana', 'ぬ', 'A noodle looping back onto the fork — nu(dle).'),
  ('hiragana', 'ね', 'A cat with a curled tail — ne(ko), Japanese for cat.'),
  ('hiragana', 'の', 'A "no entry" sign — one slash through a circle: no.'),
  ('hiragana', 'は', '"Ha!" — laughing with a hand on the hip.'),
  ('hiragana', 'ひ', 'A grin seen from the side — hee! (hi).'),
  ('hiragana', 'ふ', 'Mount Fuji puffing steam — fu(ji).'),
  ('hiragana', 'へ', 'A heap of sand with one steep side — he(ap).'),
  ('hiragana', 'ほ', 'A garden hoe leaning on a fence — ho(e).'),
  ('hiragana', 'ま', 'Mama with her hair in a bun — ma(ma).'),
  ('hiragana', 'み', 'A music note with a looping tail — mi, as in do-re-mi.'),
  ('hiragana', 'む', 'A cow''s face mid-moo — mu.'),
  ('hiragana', 'め', 'An eye — め (me) is Japanese for eye.'),
  ('hiragana', 'も', 'A hook reeling in one more fish — mo(re).'),
  ('hiragana', 'や', 'A yak''s head with one curved horn — ya(k).'),
  ('hiragana', 'ゆ', 'A letter ''U'' skewered on a pole — yu.'),
  ('hiragana', 'よ', 'A yo-yo hanging off a finger — yo.'),
  ('hiragana', 'ら', 'A rabbit''s ear flopping forward — ra(bbit).'),
  ('hiragana', 'り', 'The letters ''r'' and ''i'' side by side — り is just ri.'),
  ('hiragana', 'る', 'A winding route ending in a loop — ru(te).'),
  ('hiragana', 'れ', 'A sprinter coiled at the starting line — re(ady)!'),
  ('hiragana', 'ろ', 'る without its loop — same road (ro), lost the loop (ru).'),
  ('hiragana', 'わ', 'A wasp with a curled body — wa(sp).'),
  ('hiragana', 'を', 'Sounds like ''o'' — only ever the object particle; spot it and move on.'),
  ('hiragana', 'ん', 'A cursive lowercase ''n'' — ん literally is n.'),

  ('katakana', 'ア', 'An ''A'' missing its crossbar, swung like an axe — a(xe).'),
  ('katakana', 'イ', 'A capital ''I'' leaning into the wind — i.'),
  ('katakana', 'ウ', 'う''s angular twin: a ''u'' under a pointed roof — u.'),
  ('katakana', 'エ', 'A capital ''E'' rotated to lie flat — e, literally.'),
  ('katakana', 'オ', 'A pole with its flag torn off — o(ff).'),
  ('katakana', 'カ', 'か minus its flag stroke — the same karate kick: ka.'),
  ('katakana', 'キ', 'き without the curl — still the key: ki.'),
  ('katakana', 'ク', 'A cook''s paper hat — ku(k).'),
  ('katakana', 'ケ', 'A tilted capital ''K'' — ke.'),
  ('katakana', 'コ', 'A corner bracket — ko(rner).'),
  ('katakana', 'サ', 'Sardines laid on a grill rack — sa(rdine).'),
  ('katakana', 'シ', 'し tipped onto its back, plus two drops — shi. Flat strokes = shi.'),
  ('katakana', 'ス', 'A suit jacket tossed over a chair — su(it).'),
  ('katakana', 'セ', 'A crooked number seven — se(ven).'),
  ('katakana', 'ソ', 'One stitch sewn straight down — so (sew). Upright stroke = so.'),
  ('katakana', 'タ', 'A tadpole darting downward — ta(dpole).'),
  ('katakana', 'チ', 'The cheerleader again, gone angular — chi(eer).'),
  ('katakana', 'ツ', 'つ tipped upright, plus two drops — tsu. Upright strokes = tsu.'),
  ('katakana', 'テ', 'A one-legged table — te, as in テーブル (teeburu).'),
  ('katakana', 'ト', 'A totem pole with one branch — to(tem).'),
  ('katakana', 'ナ', 'A knife mid-slice — ナイフ (naifu) starts with it.'),
  ('katakana', 'ニ', 'The kanji 二 (two) — ni is literally "two" in Japanese.'),
  ('katakana', 'ヌ', 'Chopsticks crossing a noodle — nu(dle).'),
  ('katakana', 'ネ', 'A necktie knotted at the collar — ne(cktie).'),
  ('katakana', 'ノ', 'A single "no!" slash — no.'),
  ('katakana', 'ハ', 'The kanji 八 (hachi, eight) — same shape, free anchor.'),
  ('katakana', 'ヒ', 'A heel seen from the side — hi (heel).'),
  ('katakana', 'フ', 'Just Fuji''s summit ridge, nothing else — fu.'),
  ('katakana', 'ヘ', 'Identical to hiragana へ — one hill, two scripts, free he.'),
  ('katakana', 'ホ', 'A tree hung with ornaments — ho, ho, ho.'),
  ('katakana', 'マ', 'A map pin leaning sideways — ma(p).'),
  ('katakana', 'ミ', 'Kanji 三 (three) slanted — mi, as in mittsu.'),
  ('katakana', 'ム', 'A cow''s angular muzzle — mu (moo).'),
  ('katakana', 'メ', 'め''s eye gone angular, winking shut — me.'),
  ('katakana', 'モ', 'も gone angular — same mo, no hook.'),
  ('katakana', 'ヤ', 'や''s angular twin — same ya.'),
  ('katakana', 'ユ', 'A ''U'' standing on a baseline — yu.'),
  ('katakana', 'ヨ', 'A yoke rack seen from the side — yo(ke).'),
  ('katakana', 'ラ', 'A ramp under a flat roof — ra(mp).'),
  ('katakana', 'リ', 'り straightened out — still just r + i: ri.'),
  ('katakana', 'ル', 'Forked roots, one tip curling up — ru (root).'),
  ('katakana', 'レ', 'A razor blade seen edge-on — re(zor).'),
  ('katakana', 'ロ', 'A robot''s square mouth — ro(bot).'),
  ('katakana', 'ワ', 'An upside-down wine glass — wa(ine).'),
  ('katakana', 'ヲ', 'Sounds like ''o'' — vanishingly rare; recognize it and move on.'),
  ('katakana', 'ン', 'One flat flick — n. Flat = ン (n); upright = ソ (so).')
) as v(script, character, mnemonic)
where k.script = v.script and k.character = v.character;
